### ISSUE TITLE
Kool aid

### ISSUE THREAD

**Issue by diddledan** [notwaldorf/ama#1]
We've all heard about mythical "the kool aid", so I'm wondering the following:

- Have you ever drunk the kool aid?
- Is it tasty, and more importantly nutritious?
- Where can I get some for myself?
- Is it suitable to give to children when they're thirsty?

**Comment by notwaldorf** [comment]
I have never actually drank kool-aid, but once in high school I used the red kind to dye my hair, because I read about it in a Kurt Cobain biography. It looked terrible, and it's probably just as nutritious as hair dye.
