### ISSUE TITLE
What book should I read after the book we got tonight?

### ISSUE THREAD

**Issue by jlord** [notwaldorf/ama#10]
📚🇨🇦

**Comment by notwaldorf** [comment]
I will only answer this if you fix the contribution graph to give me a square for resolving this issue :trollface:

**Comment by jlord** [comment]
lol not my department! 💁

In other news a person on the subway in NYC told me that my book was out of date and I should pick up a newer one of his. 

In other, other news I learned about the [Neapolitan Series](http://elenaferrante.com/) and was told _everyone_ was reading them so I picked up the first one and started it.

**Comment by notwaldorf** [comment]
Uhmmm we should probably start an online book club. Just saying. We can give it a github repo and everything
