### ISSUE TITLE
Interested in ML? 

### ISSUE THREAD

**Issue by builtbyproxy** [notwaldorf/ama#100]
Hey Monica

I've seen in my activity feed that you've been forking and messing with ML based repositories! Did you have a specific project/idea you were looking into this for or did you just want to wrap your head around ML? 

A bit of an ambiguous question but I'm interested to hear where this could lead

Thanks

~Lachlan

**Comment by builtbyproxy** [comment]
Update, she now works at [Magenta](https://magenta.tensorflow.org/)
How Cool!

**Comment by notwaldorf** [comment]
Oh yeah! Sorry, when you asked the question the first time the news wasn’t quite public yet, and then I forgot to come back to it! Yeah, I’m super interested in ML and in particular how we can use it to help people unleash their creativity :)

**Comment by builtbyproxy** [comment]
Love it! Thats all good I was bummed to not seeing you presenting at the chrome dev summit, now I know why haha

Huge congratulations, its awesome to work on something youre passionate about, cant wait to see what you do in the space!
