### ISSUE TITLE
Why 'notwaldorf'?

### ISSUE THREAD

**Issue by shrayasr** [notwaldorf/ama#102]
AHOY ✨ Monica ✨ 

Thanks for doing this! You're awesome and I've learnt a lot by following you and reading stuff you've written and talks you've given. 

Although I've always had a question -- Why **notwaldorf**?

**Comment by sushant-j** [comment]
Just stumbled on this question, and while @notwaldorf might answer further, here's a previous answer she's written :)

> The Muppets! My favourite two characters from the show are the grumpy old men, Waldorf and Statler. In university, my best friend and I were basically them, so in all the internets things I am "not waldorf" (because I'm not actually him), and she is "maybe statler" (spoilers: she isn't either). :)

_- from https://github.com/notwaldorf/ama/issues/13_

**Comment by notwaldorf** [comment]
that's exactly right!

**Comment by shrayasr** [comment]
I searched for "notwaldorf" before I posted this question but clearly didn't look for "not waldorf" or "username" 😅 

Thanks for answering this, @sushant-j and @notwaldorf

**Comment by dandv** [comment]
All along (7+ years, since I was also at Google working in DevRel on PWAs), I thought "not waldorf" differentiated you from some famous "Monica Waldorf" (turns out there isn't really one)
