### ISSUE TITLE
Would you like to speak at JSConf.Asia next year?

### ISSUE THREAD

**Issue by huijing** [notwaldorf/ama#103]
Hello Monica,
Don't know if you remember me, but we spoke briefly at Webconf.asia earlier this year. I'm part of the team organising JSConf.Asia next year, and we were wondering if you'd be interested in coming over to Singapore to give a talk? We're scheduled for 14-16 June, with talks, workshops, generative art displays (venue is an art college), and some other cool stuff we're planning.
If this does pique your interest, our CFP form is at: https://contribute.jsconf.asia/, which we use for tracking and planning. I really hope you'll consider it :)

**Comment by notwaldorf** [comment]
I would! I'm going to close this since there's a separate email thread now. 😅
