### ISSUE TITLE
Polymer 3.x Cheat Sheet.

### ISSUE THREAD

**Issue by Tatachiblob** [notwaldorf/ama#105]
I recently started learning Polymer and I stumbled upon your posts. I was wondering if you would make a 3.x cheat sheet.

**Comment by notwaldorf** [comment]
Unfortunately, I don't work on Polymer anymore, so I'm not super up-to-date with all the final changes in 3.x. Maybe @e111077 or @katejeffreys will make one, if you ask them nicely 😅

**Comment by Tatachiblob** [comment]
Ah I see. I still appreciate for the 2.x cheat sheet since I made a lot of progress with my own project. Thank you for the kind reply.
