### ISSUE TITLE
future of tiny-care-terminal

### ISSUE THREAD

**Issue by mojoaxel** [notwaldorf/ama#107]
Hi Monica,

The last release of the [tiny-care-terminal](/notwaldorf/tiny-care-terminal) is OVER 9000....eh....9 month old. 
Can you please release a new version of the current master. :pray: 
Alternatively you could grant me npm-access, I'm willing to have an eye on new issues and pull-requests, like I did last year. :wink: 

Hope to see you again at #jsconfeu this year,
Alex

**Comment by notwaldorf** [comment]
Yeah, the future of tiny-care-terminal is looking grim eh. I don't see anything on the npm page about adding a different person, and on github you're already a collaborator with push access so ummmm i don't know how!

**Comment by notwaldorf** [comment]
Oh, figured it out on the command line! You're listed as a collaborator now, 🤞🤞🤞
