### ISSUE TITLE
Home desk setup

### ISSUE THREAD

**Issue by snowiesuet** [notwaldorf/ama#109]
Hello! I saw your tv setup from your twitter (the photo of your 🐱watching 🚀) and I'm curious how your home desk setup is like. 😆 

PS: My first open issue ever on Github!

**Comment by notwaldorf** [comment]
Oh gosh, I'm so sorry for taking so long on replying to your first issue! I'm very bad at monitoring this repo.

My home setup is, in theory, a desk, a laptop stand and one of 4 mechanical keyboards connected to it, but in practice me sitting on the floor in my living room in a corner next to power. I find my office feels too formal and not quite comfortable enough (chair is a bit too short, mouse is a bit too slow, etc) that I haven't quite found my groove yet. I'll try to remember to add a photo today!

**Comment by notwaldorf** [comment]
Here's a photo of the desk setup --pretty sparse! There's not one but TWO dog crates in my office (one where the dog sleeps, one where the dog used to sleep before she grew and couldn't fit in it and we haven't got rid of it). Maybe this is why i don't work in here, hmmm.

![IMG_0472](https://user-images.githubusercontent.com/1369170/66959723-d6ce2f80-f01f-11e9-9100-2bfa1e34c347.jpeg)
