### ISSUE TITLE
Invitation to speak at Codemotion Milan - October 24, 25

### ISSUE THREAD

**Issue by dekramobile** [notwaldorf/ama#111]
Hi Monica,

My name is Matteo Bonifazi, and I am DevRel Manager of Codemotion,
I'm writing because we would be thrilled to have you as our speaker in our  
upcoming Codemotion conference, Codemotion Milan 24-25 October!

Here's a video of Codemotion Milan 2018 ( link: https://www.youtube.com/watch?v=Xk19mqG6p54 ) so that you can have an idea about the enthusiasm and the spirit of our conference!

Looking forward to hearing from you soon.
Have a great day

**Comment by notwaldorf** [comment]
Closing this since I replied on an email :)
