### ISSUE TITLE
Looking for one of your old Polymer videos

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#113]
I recall one of your older Polymer videos(maybe a Summit?) on youtube where you emphasised dataflow to go downward in one way binding and data upward using events. 

This would be great for my team if I could show them it. I have been going through your videos but can't find it. By any chance do you remember which video?  I know there is also `data flow` by Gary Norton but I would like to use your video also if I can find it.

**Comment by notwaldorf** [comment]
Hiya! I think it's this? https://youtu.be/Ihdp63FaRKA?list=PLaTVuY0k20c34tMS9zodzkVKzr00Br-Rw&t=1433! I feel I've been saying this for a while, but this might be the first time?

**Comment by dman777** [comment]
Yep, thanks!
