### ISSUE TITLE
Wecomponents testing for Polymers

### ISSUE THREAD

**Issue by vdabur01** [notwaldorf/ama#114]
I have used autocomplete_component on my page and now I have to write test cases for that. I have gone through many webcomponents testing links and videos, but still I am not very clear on concepts of testing for webcomponents. Can you help me in this ?

**Comment by notwaldorf** [comment]
I no longer work on the Polymer team, so I no longer know if [web-component-tester](https://github.com/Polymer/tools/tree/master/packages/web-component-tester), which is what I used to use, is the thing you should use.

I recommend seeing if that is up to date and using that (and filing bugs on that repo if things aren't clear).
