### ISSUE TITLE
Speaking at Frontend United 2020

### ISSUE THREAD

**Issue by ezenko** [notwaldorf/ama#117]
Hello Monica,
We tried to approach you via email, but without success.

Maybe this will work :)

Hello Monica!
My name is Yauhen Zenko. I am a volunteer organiser for the Frontend United Conference in Minsk, Belarus in 2020, tasked with organising speakers for this year’s conference. 

In this message I will be:

- Asking if you would speak at our conference, and
- Offering to cover your travel and accommodation costs, and
- Offering you a speaker’s fee for your effort
- Hoping you are interested so far. If so … read on.

About Frontend United
Frontend United is a not-for-profit, medium-sized (about 500 attendees), roving conference - each year it is in a different European city. In previous years it has been in Utrecht, Athens, Ghent, Bristol, Copenhagen and many others. This year, it will be in Minsk, Belarus from May 1st to May 2nd as well as a workshop day on April 30th.

Our Ethos, Helped by You
Frontend United aims to create an event that reflects the diversity of topics, challenges and people currently interested in frontend development and technology. We would love if you could be part of creating that vision with us this year! We're convinced your level of expertise would be a great addition to our line-up. If you’d like some background on the range and quality of speakers and topics we include, you can view the videos of all sessions from last year’s conference in Utrecht. We have created a blog post about our values, if you would like to read more.

What We Offer
As mentioned at the outset, if you are interested in speaking at our conference (this is the bit where we are asking you to be a speaker!), Frontend United can cover your cost of travel, your accommodation costs in the designated conference hotel (which we will ensure is close to the venue), and pay €500 for a speaker’s fee to you (or a nominated charity if you wish), if you need us too. Some speakers speak for free or get sponsored by their employers, allowing us to use that money to make the conference even better or provide tickets for less-privileged attendees at reduced prices or for free.

A Workshop from You?
If you would like to give a workshop in addition to your talk, this is possible on the day prior to the event. Frontend United will arrange the venue and necessary equipment. When our speakers host workshops, we offer 50% of the profits to the speaker and 50% to the conference to cover our costs as a non-profit organisation. In the case of the conference having a surplus of money after paying our expenses, we will use that surplus to make Frontend United 2021 even bigger and better than 2020!

Let Us Know
If the above looks good to you, please let us know as soon as possible, so we can start making arrangements from our side. If you are not interested, could you please also let us know. If you have any questions, we’d be happy to hop on a video call with you to go through the details.

Thanks so much, and kind regards,

Yauhen Zenko.

**Comment by ezenko** [comment]
Last year's videos: https://www.youtube.com/watch?v=RVdW-P_oAJ0&list=PL7xqy2B8uXNIA5s-1LZm6B2uIMYwyY7nb
Our moral compass: https://medium.com/@frontendunited/the-direction-of-our-moral-compass-38ff2fa6b886

**Comment by notwaldorf** [comment]
Replied by email!
