### ISSUE TITLE
Mechanical Cables 

### ISSUE THREAD

**Issue by dman777** [notwaldorf/ama#119]
Since you are into mechanical keyboards... are you also into mechanical cables? I just stumbled upon them a few weeks ago and they look sick! 

![image](https://user-images.githubusercontent.com/887815/79703473-a89d0700-8271-11ea-91e8-c76dc14776e9.png)

**Comment by notwaldorf** [comment]
Oh cool! I'm honestly really not -- I've had a bit of a hard time with cables in general, so even though I wish I had super pretty wires for my keyboard, I've sort of given up. 

Not all usb-c to usb-c wires, for example, work on all keyboards, and in particular i have a usb-c wire (from massdrop) that works on one usb-c keyboard but not the other one! Isn't that bonkers??? I know I could look into the specs to figure out why that is buttttttt I don't want to, so here I am, with the ugly cables.
