### ISSUE TITLE
Are there any other places browser styles are defined besides the user agent stylesheet?

### ISSUE THREAD

**Issue by faraixyz** [notwaldorf/ama#121]
Hi,

I first want to thank you for your article on how [[hidden] is a lie](https://meowni.ca/hidden.is.a.lie.html) which helped me fix a problem I was having.

Your article mentioned that the "rule is a User Agent style, which means it's less specific than a moderate sneeze" and the HTML spec says it can be implemented in CSS. I tried looking for a rule like `[hidden]` in the various browser default style sheets ([Chrome](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css), [Webkit](https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css)) and I couldn't find it.

Are some styles defined outside of this stylesheet?

Thanks again for writing the article, it really helped.

**Comment by notwaldorf** [comment]
This took some sherlocking! I know that for Chrome, for example, there are a bunch of other css files in [that folder](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css), such as [quirks.css](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/quirks.css), but I couldn't find `[hidden]` in any of those! 

At this point I was super curious, so I nerdsnipped @tabatkins, who said that based on what Elliott said in [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=566168#c10), presentational hints aren't applied in the user stylesheet but instead they're manually applied [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/element.cc;drc=56aab14f391a27e35a6188c15f4fa262cb898491;l=6270?originalUrl=https:%2F%2Fcs.chromium.org%2F). Then they did more digging and found that it's set [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/html/html_element.cc;l=301;drc=56aab14f391a27e35a6188c15f4fa262cb898491;bpv=1;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F), namely this gem:

```js
if (name == html_names::kHiddenAttr) {
  AddPropertyToPresentationAttributeStyle(style, 
     CSSPropertyID::kDisplay, CSSValueID::kNone);
}
```
You can look into that file to find more styles that are set this way (just look for where else `AddPropertyToPresentationAttributeStyle` is called). Whew, mystery solved. 

This was fun, thanks for asking this!!!
