### ISSUE TITLE
Check out Bongo Cat VSCode extension

### ISSUE THREAD

**Issue by pompomon** [notwaldorf/ama#122]
Hello @notwaldorf !
I know that you are a fellow cat fan, so I wanted to share with you my pet-project (or more like cat-project) :D  https://github.com/pompomon/vscode-extension-bongo-cat which adds animated Bongo Cat decoration to VSCode editor
I haven't publish it to VSCode Marketplace yet, so now it's distributed using .vsix in the releases.

Please let me know what you think whenever you have time :)

**Comment by notwaldorf** [comment]
heh, that's cute!
