### ISSUE TITLE
Be a guest on Codetalkers

### ISSUE THREAD

**Issue by martinjakubik** [notwaldorf/ama#123]
Hi Monica!

A friend and I run a podcast called Codetalkers. We chat with developers + related roles about code, tech, business and whatever comes to mind. We're starting our sophomore year and we'd love to have you in this year's lineup if you were available.

It's a ~30-minute chat. We live at codetalkers.buzzsprout.com if you want to take a look. What do you think of coming on the show? Here are a couple of ideas to talk about: the evolution of web standards (are we in a good place, where is the web headed, etc), what being an engineer at Google is like, or hey why not art + ML? (the magenta project looks really cool!)

(This is a cool way to get in touch by the way.)

Let me know if you're interested!

**Comment by notwaldorf** [comment]
I replied via email!
