### ISSUE TITLE
Feedback friend of tiny-care-terminal

### ISSUE THREAD

**Issue by davidguenin** [notwaldorf/ama#125]
Hello Monica,

A few days ago, I launched a project and I have just seen that it is close to one of yours.
So I would be very happy if you could give me a quick feedback :)

It's called Nectune, I'll let you discover it.

--> https://www.nectune.com
--> https://github.com/davdevdesign/nectune

Thank you in advance.

David from France

**Comment by notwaldorf** [comment]
Oooof, all of these links look broken 6 months later (when I finally got around to reading this question 🤦‍♀️ ). I'm sure it was neat!
