### ISSUE TITLE
Where to start learning about Magenta and music generation in general?

### ISSUE THREAD

**Issue by lucis** [notwaldorf/ama#127]
Hey @notwaldorf! First of all, I'd like to say I love your work :)

So, I'm a software engineer and have been developing on the web for a long now (used Polymer for a bit also). I'm also a passionate musician and have always been interested in joining these areas of expertise.

I'm a fan of the Magenta project and would like to know **how can I start learning about the music creation process**, specifically using web technologies. I have some experience with ML (mostly in college), but I think I'd have to study more about how we work with it with music/audio. One thing, in particular, I'm interested in learning is about music representation on the current frameworks/libs. 

Any courses, books or articles would be of great help!

Thanks,

**Comment by notwaldorf** [comment]
Thanks for the kind words! I think your best bet is to look at magenta-js github repo, and a lot of the [demos](https://magenta.tensorflow.org/demos/web/) built with it. Pretty much all of them are open source, so you can look at how they work and how they use the models, and see where you want to go with from there.

For music representation, most magenta models are all about MIDI, which translates really nicely to manageable objects: https://github.com/magenta/magenta-js/blob/master/music/src/protobuf/proto.js#L30
