### ISSUE TITLE
Is computational creativity a viable field to pursue? 

### ISSUE THREAD

**Issue by Pipe-Runner** [notwaldorf/ama#128]
I love computers, I love maths, I love arts. All that comes to my mind is computational creativity. But amidst the storm of ML/DL and all the fancy buzzwords, it seems like the field of computational creativity is dead. I want to pursue my MSc in something I am passionate about, but also, I don't want to end up on the streets after my MSc; if you know what I mean.

**Comment by notwaldorf** [comment]
I'm not sure how to answer that! When I went to school computational creativity wasn't even a thing (or if it was it didn't reach undergrads 😅). I think the question you want to ask yourself is do you want to be an artist in the future (i.e. focus on making art with computers), or a computer person who sometimes makes art (so your day job isn't necessarily your art passion). It's a very personal question and I don't know what I would pick! In my experience, being passionate about what you work on burns you out eventually, and getting burned out by art feels a lot more hard to recover from (and may we never experience it!!!). 

Re: ML/DL and the fancy buzzwords: someone's gotta use all those models in cool and novel and creative way, and visualize what they do; far more people imo than the people doing the hardcore research or training the models, who generally aren't on the visual arts side.

**Comment by Pipe-Runner** [comment]
Beautifully put. Thank you for answering. :)
