### ISSUE TITLE
What does your username mean?

### ISSUE THREAD

**Issue by eush77** [notwaldorf/ama#13]
Is it a reference to something? Why did you choose it?

**Comment by notwaldorf** [comment]
The Muppets! My favourite two characters from the show are the grumpy old men, Waldorf and Statler. In university, my best friend and I were basically them,  so in all the internets things I am "not waldorf" (because I'm not actually him), and she is "maybe statler" (spoilers: she isn't either). :)

**Comment by eush77** [comment]
How sweet! Thanks.
