### ISSUE TITLE
What’s up Monica?

### ISSUE THREAD

**Issue by yishengjiang99** [notwaldorf/ama#130]
How you doing?

**Comment by LILOGBBBANGINONTHEWALL** [comment]
Good , same shyt different toilet..

**Comment by notwaldorf** [comment]
Oh hey, not much, not much. I'm doing a bit of freelancing at the moment, and a bunch of art on the side, which is a very different pace from 50h of software engineering a week. Thanks for asking!

**Comment by LILOGBBBANGINONTHEWALL** [comment]
Hey anything new in your plate

**Comment by LILOGBBBANGINONTHEWALL** [comment]
42
