### ISSUE TITLE
Has Anyone Told You They Read Your Posts In The Voice Of John Mulaney? 

### ISSUE THREAD

**Issue by mathyouf** [notwaldorf/ama#131]
This is an urgent question, please respond with the appropriate haste. I need to know I'm not alone in the universe.

**Comment by mathyouf** [comment]
Here's a picture of my dog btw

![56340128_10156594481823743_8573413257266593792_o.jpg](https://user-images.githubusercontent.com/19615875/152854053-c607e0f2-44b6-4cf9-ae22-bbcc5966ff27.jpg)

**Comment by notwaldorf** [comment]
I don't know how to feel about that... His voice is a bit cartoonish. But then again: so is mine 😂
