### ISSUE TITLE
"Keypress is bananas" - bit of further info

### ISSUE THREAD

**Issue by JanneM** [notwaldorf/ama#16]
Tried the example code in your post "keyypress is banas". Ran Firefox 41.0.2 and Chromium WeAreTooCoolForAboutDialogs, both on Ubuntu 14.04LTS. Both work much as you describe, but with a few twists. 

* The Enter key - not printable AFAIK - and control-enter does render a keycode under Chromium. For Chromium, ctrl-enter is keycode 10, while both Enter and ctrl-Enter is keycode 13 under Firefox. Oh, on the numpad, Chromium gets the Enter event but not the ctrl-enter one.

* Using the Compose key (to write things such as ß, …, —, ō) generates no key events of any kind on Chromium or Firefox. Neither does entering Unicode codepoints directly (ie. alt+shift+u, then a four-digit hex number). Nor does things like accented characters ("´"+e = é generates no events at all). Unicodey characters generated directly from single keypresses (åäö with a Swedish keyboard for instance) do work. 

* Using Japanese input - 漢字とかひらがなとか - never generates any events at all. It's not an input method issue; writing "regular latin" using the Japanese input method generates events as usual, while "ｗｉｄｅ　ｌａｔｉｎ" does not. Nobody would argue that these are not printable characters. BTW, I can easily enter any regular latin string without any key events generated by using the kana conversion key.

So, keypress events work as long as you 1) don't want to care about any language beyond English or related Western ones, any names or words with accents or diacriticals, or people using anything but a regular Latin keyboard input; and 2) don't mind that your users can trivially bypass your keypress detection at will. 

Don't use it for counting characters or for input validation in general in other words. Not sure what you would use it for, seeing how it behaves.

**Comment by notwaldorf** [comment]
Oh my goddddddddd, it's madness all the way down. Thanks for this! I hadn't even thought about non-English languages. Keypress: not even once. :)

**Comment by lozandier** [comment]
@notwaldorf What are quirks you've seen in your career associated w/ `beforeinput` and `input` as substitutes to `keypress` and `keyup`?

**Comment by notwaldorf** [comment]
I have never used `beforeinput`. My understanding is that `input` is fired after a character has been added to the control, which is strictly not the same as `keydown`/`keyup`: imagine that you want to prevent spaces from being added to a control: you want to do this before the space is added to the value (so on key-something), rather than adding-and-then-removing (which is what you have to do in `input`)
