### ISSUE TITLE
How would one go about changing their Chrome settings button into an emoji?

### ISSUE THREAD

**Issue by venoma333** [notwaldorf/ama#17]
_I'm asking for a friend_

**Comment by notwaldorf** [comment]
Have an emoji/combination of emojis copy pasted at the ready. Click on the profiles menu to open the dropdown, and click on your current name to make it editable (when you hover over your name, a pencil icon should appear):
<img width="272" alt="screen shot 2015-10-23 at 10 41 52 am" src="https://cloud.githubusercontent.com/assets/1369170/10700475/c6c633da-7972-11e5-809b-71b093861283.png">

 When it's editable, paste your :sparkles::space_invader::pizza: and bam. Emoji in your browser.
