### ISSUE TITLE
Have dear-sir-or-madam run on every page load

### ISSUE THREAD

**Issue by MikkelSandbag** [notwaldorf/ama#18]
Is it possible to have that script run on every page load? I may or may not want to prank my co-worker... >:)

**Comment by notwaldorf** [comment]
You would need to make a Chrome page extension that loads on every page. Here's my [twemoji](https://github.com/notwaldorf/twemojify/tree/master/extension) that does something similar. I think all you would have to do is replace the contents of `twemojify.js` with `ransom-it.js`, and install it as a Dev extension :)
