### ISSUE TITLE
Thank you for noms.

### ISSUE THREAD

**Issue by ShivanKaul** [notwaldorf/ama#28]
Was browsing for [ECSESS](http://ecsess.mcgilleus.ca/)'s current reps but Google redirected me to [this](http://www.excess.ece.mcgill.ca/reps.htm).

A DFS of hyperlinks later I discovered [this](https://www.youtube.com/watch?v=SMWi7CLoZ2Q) because of you. I have my COMP 360 final in 5 hours but I can't stop listening.

THANK YOU.

**Comment by notwaldorf** [comment]
Ha! Glad I could be of help! 😹 
Congrats on being done with COMP 360 🎉
