### ISSUE TITLE
What is your favorite emoji?

### ISSUE THREAD

**Issue by stoeffel** [notwaldorf/ama#3]
^^

**Comment by notwaldorf** [comment]
Ugh, I have so many. Probably ✨. Runners up are 😻and 😭.

**Comment by mathiasbynens** [comment]
Since 2015 many new emoji have been introduced. Did your emoji top 5 change in the past few years?

**Comment by notwaldorf** [comment]
Since android deprecated the blobs, I’ve become obsessed with the [dancer](https://emojipedia.org/google/android-5.0/dancer/) emoji because it is perfect and sassy. Also keen on👩‍🎤 (lady bowie).
