### ISSUE TITLE
advice and stuff

### ISSUE THREAD

**Issue by jlipkin8** [notwaldorf/ama#33]
Oh hey! I don't remember how I cam across your github account, but IT HAS SOME FUN STUFF. So I'm taking an class at a local community college that requires us to contribute to an open source project. I'm very beginner when it comes to code. I know some JavaScript, made it a few chapters into Eloquent JavaScript and I know some C++( I am taking a C++ Data Structures and Algorithms class) so that's where I'm at. Do you have any advice for finding open source projects that a beginner can comprehend and possible contribute to? Thanks!

**Comment by notwaldorf** [comment]
Hiya! Yay, glad you like it! Sorry I missed responding to this; I saw it, and then there was a code fire, and then it got lost in the cave that is my inbox! 😓

By the way, Eloquent JavaScript is the best! It's my favourite intro book to anything ever, so 👍 to that. 

Here's a bunch of sites I can think about that might help with finding a project:
- [Your first PR](https://twitter.com/yourfirstpr) is a twitter account that shares good-first-issues whcih are available for people to work on
- [24 pull requests](http://24pullrequests.com/projects) has a list of projects that are looking for contributions. The `help-wanted` tag usually indicates good first bugs. Documentation bugs are always good first things to work on too (and PRs that the project maintainers will be eternally grateful for 🍰) 
- [Openhatch](https://openhatch.org/) is another similar "search for projects who want contributions" site

If you just want to practice and have fun programming, then 
- @rmurphey recently released a couple JS [exercises for beginners](https://rmurphey.com/blog/2016/02/13/exercises-for-js-beginners), which are fun side projects to work on
- In the same theme, @jendewalt did a neat thing where she made [180 websites in 180 days](http://jenniferdewalt.com/). You could always look at the ones she did, and try to code them yourself if you want more practice. Some are super fun!

Hopefully one of these will work out for you! Let me know if they don't, I can try to think of more!

**Comment by jamesxv7** [comment]
Something that has worked form me is the [Changelog Nightly](https://changelog.com/nightly/) newsletter. It is basically a list with the latest popular repo in Github. Many of these repo still have not reached the stardom and most require help. Usually you can find very interesting things in that letter. 

Happy coding!

**Comment by jlipkin8** [comment]
Thank You!!!!
