### ISSUE TITLE
Competitive Programming

### ISSUE THREAD

**Issue by aajjbb** [notwaldorf/ama#35]
Hi, 

To start, I really enjoy your posts and repos, keep up the good work!

I'd like to know your opinion about Competitive Programming ?

Thanks :)

**Comment by notwaldorf** [comment]
Blerg. So in high school I went to a bunch of math/programming competitions and I really, truly, hated them. I don't really enjoy having to solve arbitrarily hard problems in an arbitrarily short period of time. I have the same problem with programming interviews nowadays too -- I find them very stressful, get incredibly nervous, and I notice that I perform significantly worse than if you just gave me an evening to solve a harder problem, but left me alone.

There's a bunch of people who have tons of fun at them, and I really respect that. I just think that much like sports and athletics, they're probably not everyone's cup of tea 😊
