### ISSUE TITLE
If you could change three things about Polymer..

### ISSUE THREAD

**Issue by addyosmani** [notwaldorf/ama#37]
What would they be? :cake: ..and it can't be more people working on the paper elements :joy:. That would be cheating.

**Comment by mahirdar** [comment]
As a new learner, I'm not sure about routing issues but can't Polymer's PageJs provide the features app-router, excess-router provide in PSK?

**Comment by notwaldorf** [comment]
@addyosmani What a nice and inflamatory question, Addy! :) 

As an element writer, I'd like an easier way to pinpoint performance problems. I've sort of become obsessed with performance, and while _I_ know that creating DOM that you don't need at render time is bad, I'd like there to be a magical guide or tool that says "in your tests you're never using this one div, are you sure you shouldn't be lazily instantiating it?"

As an element user, I'd like a better way to understand all of the mixins or behaviours that apply to my element (which can come from nested elements, and makes aggregating this data really hard). 

As Chief Emoji Officer, I'd  obviously like to be able to use emoji in element names, but that needs a spec change probably.
