### ISSUE TITLE
Are you aware of Instagram's Emojineering efforts?

### ISSUE THREAD

**Issue by addyosmani** [notwaldorf/ama#38]
If not, now you are:

- https://vimeo.com/138662641
- http://instagram-engineering.tumblr.com/post/117889701472/emojineering-part-1-machine-learning-for-emoji
- http://instagram-engineering.tumblr.com/post/118304328152/emojineering-part-2-implementing-hashtag-emoji

Also, you're welcome :cookie:

**Comment by notwaldorf** [comment]
HOLY CRAP I WASN'T. BRB, moving to Finland, capital of Emoji.
