### ISSUE TITLE
Advise or recommendation when creating slides?

### ISSUE THREAD

**Issue by olbpetersson** [notwaldorf/ama#39]
Hi Monica,

Saw you last year at Öredev, great and inspiring presentations!

For some reason I stumbled upon https://speakerdeck.com/notwaldorf and your slides look really good. Are you using any service (like pivotal) to put together your slides or have you created them all from scratch (with themes, fonts etc)?

**Comment by notwaldorf** [comment]
Thanks! Glad you like them!

I really like designing slides, so I make them all from scratch, in Keynote. Here's a bunch of resources I found helpful when I was starting out:
- I get my fonts from either Google fonts, [League of Moveable Type](https://www.theleagueofmoveabletype.com/) or [Lost Type Co-op](http://www.losttype.com). The last two are really nice donation based type foundries
- @holman's [speaking.io](http://speaking.io/) is full of good advice on slide design and organization -- I stole a lot of tricks from there
- I tend to use my own photos, but Flickr has a bunch of Creative Commons licensed photos that you could use, provided you attribute them correctly. [The noun project](https://thenounproject.com/) is also really good for free icon-y looking things 😊

Hope these help! Happy slide designing! ✨💻🎉
