### ISSUE TITLE
Why are you emojineer and not engineer?

### ISSUE THREAD

**Issue by amitmerchant1990** [notwaldorf/ama#4]

**Comment by notwaldorf** [comment]
Ha! That's actually @addyosmani's doing. I am an engineer and I make a lot of obnoxious [projects](https://github.com/search?q=user%3Anotwaldorf+emoji) about emoji (also, just know way too much about emoji in general), so Addy decided that makes me an emojineer.

Also titles are silly, and my previous one was "code meerkat".
