### ISSUE TITLE
Which technical book(s) / articles would you recommend?

### ISSUE THREAD

**Issue by vlvagerviwager** [notwaldorf/ama#40]
Are there any technical books or articles you learned a lot from, or fundamentally changed the way you work? I'm a Java platform dev who recently defected to web development, currently reading The Pragmatic Programmer 📖🌱

**Comment by notwaldorf** [comment]
That's a good question! I can't think of any tech books off the top of my head -- I think I read some when I was younger when they were relevant to my job (like Working Effectively with Legacy Code by Michael Feathers back when I worked in an investment bank), but there's nothing that I've read recently 🤔. I've definitely read The Pragmatic Programmer and it was great!
