### ISSUE TITLE
Chromium link to your blog is broken. Intentional?

### ISSUE THREAD

**Issue by montj2** [notwaldorf/ama#41]
Hi! 

The official Chromium site[0] has a link to your blog[1] on how to go from 'zero to hero' that appears to be broken :frowning: 

Using the Wayback Machine I found a snapshot[2] dated 12 February 2016. I'm going to use this as my guide unless you have a reason for its removal - like 'zomg, outdated and terrible' or 'I'm in the process of updating it". 

Thanks! :smile: 

0: https://www.chromium.org/developers/how-tos/get-the-code
1: http://meowni.ca/posts/chromium-101/
2: https://web.archive.org/web/20150926170519/http://meowni.ca/posts/chromium-101/

**Comment by notwaldorf** [comment]
@montj2 Argh. It's the trailing slash! http://meowni.ca/posts/chromium-101 is just fine, http://meowni.ca/posts/chromium-101/ is hosed. :(

Apparently @github switched to Jekyll 3 which breaks trailing slashes. Trying to fix 😭

**Comment by notwaldorf** [comment]
Alright! I think I fixed this! Thanks! 🎉
