### ISSUE TITLE
Emojineering advice

### ISSUE THREAD

**Issue by Mottie** [notwaldorf/ama#43]
Hi @notwaldorf!

I too <img title=":_ love_dizzy :" src="https://cloud.githubusercontent.com/assets/136959/13512433/3d478a5e-e160-11e5-96fa-5add6196a37e.gif"> emojis, enough so that I don't think there are enough emojis in the world (<img title=":_ gimme :" src="https://cloud.githubusercontent.com/assets/136959/13512391/f24f145e-e15f-11e5-9435-9a7782db22b8.gif"> more)! 

<img title=":_ onion_head_lol2 :" src="https://cloud.githubusercontent.com/assets/136959/13371599/b87a55d2-dcef-11e5-9640-02a14877cdb3.gif">

Anyway, I <img title=":_ typerhappy :" src="https://cloud.githubusercontent.com/assets/136959/13512575/13c2dbd8-e161-11e5-8205-436e6ab9b70a.gif"> a userscript to work on GitHub - ["GitHub Custom Emojis"](https://github.com/StylishThemes/GitHub-Custom-Emojis)" - I would be really <img title=":_ happy :" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif"> to know what you think.

< (^^,) >

**Comment by notwaldorf** [comment]
Heh, neat! They remind me a lot of old chatroom animated smileys :)
