### ISSUE TITLE
Whats your recomendation?

### ISSUE THREAD

**Issue by BalbuenaJuan** [notwaldorf/ama#45]
First of all sorry for my bad english. My question is about which books about programming you recommend to initialize if I don´t have notions of algorithms and hard control structures. I only know HTML, CSS and a little of JavaScript (I really enjoy JavaScript). BTW I have the Eloquent JavaScript book and I´m reading that and is fantastic. You can recomend me 3-4 books to start?. Thanks

**Comment by notwaldorf** [comment]
Eloquent JavaScript is my faaaaaavourite book to learn a language. It's written so well! Unfortunately I learnt algorithms in school, so all I know are textbooks, most of which are terrible. There's an enormous book called "Introduction to Algorithms" by Cormen et al that has literally everything you could ever want about algorithms and data structures. If you do a little bit of googling, you can find a pdf of it online. :)

"The Pragmatic Programmer" is also a good read, for a "how to be a good programmer" sort of perspective.

**Comment by abdulhannanali** [comment]
@BalbuenaJuan I would also recommend definitely giving [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS) by @getify a read, you will learn a lot about JavaScript.
