### ISSUE TITLE
Is it possible to change silly OEM emojis for Nicer Ones?

### ISSUE THREAD

**Issue by ssaavedra** [notwaldorf/ama#47]
Since you know a big deal about emoji, work at Google and seem to like the Android emoji font, I can't think of a better person to ask this to.

I have a Samsung tablet, and I am really disappointed with their emoji font 😞. It takes all the fun apart. I would really love it if I could change the font to the Android stock emoji, which at least are consistent with other Android users, so that at least I can know what are people trying to send me. So, I was just wondering if that is possible. If not as a normal user, I am willing to root the thing anyway just to have some fun. 💥

Also, a smaller thing: why do the Hangouts emoji set change so much? The Android app is not even keeping track of the emoji available on the web version. 💭 maybe the emoji glyphs changed with different Android versions?

And please, don't remove the cuter smiling emoji (I don't know how to refer to it by name). It's much more cute than the standard ":-)".

Comparison: ![](http://i.imgur.com/gDVTm8A.png)

**Comment by notwaldorf** [comment]
Ooof, that sounds hard. I think the default emoji font comes from the OS, so I think you'd have to either root it, or install an app that somehow rejiggers the fonts. I don't know anything about that, but some brief [googling](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=change%20samsung%20emoji%20font) ("change samsung emoji font") has [this](http://wccftech.com/leak-samsungs-galaxy-s6-active/) as the first result. I would double check what permissions these app install, as they might be a bit bonkers :(

I don't really have any influence (or knowledge) about how the fonts change -- I [read](http://www.theverge.com/2016/4/16/11441876/android-n-new-emoji-closer-look) that in Android N a bunch of the blobs are changing to match the iOS emoji, but I literally found that out from Verge :)

Sorry I couldn't really be of help!
