### ISSUE TITLE
Becoming an ✨Emojineer✨

### ISSUE THREAD

**Issue by andreicek** [notwaldorf/ama#49]
Hi!

I would like to be an ✨Emojineer✨ at my company ([@Infinum](https://github.com/infinum)). I just wanted to run it by you if that is fine with you. 😃 

Thanks!

**Comment by notwaldorf** [comment]
Oh, of course! Anyone can and should be an 💥✨emojineer✨💥!

**Comment by abdulhannanali** [comment]
Okay, everyone, I am a self proclaimed unemployed emojineer. :sparkles: :heartpulse: :zap:
