### ISSUE TITLE
Help finding a great JavaScript engineer

### ISSUE THREAD

**Issue by vanjiminster** [notwaldorf/ama#50]
Hello Monica,

Hope you're doing well. This is Jimmy. We worked together at Morgan Stanley a while back - I was an intern. 

I co-founded a startup last year, and things are starting to take off now. We've gotten some seed funding, and we've got a great team: MBA student + PhD student (myself) + McGill professor.

We're currently looking for someone to help us take our front-end mobile app to the next level. We're using the ionic framework, and the app uses AngularJS. Do you know anyone in Montreal who could fill the role? We have money to pay.

You could get back to me at jimmyli AT cim.mcgill.ca

(I intentionally left out details of what we do since this post is public)

Thanks,

Jimmy

**Comment by notwaldorf** [comment]
Sorry, I no longer live/work in Montreal. Good luck with the search!
