### ISSUE TITLE
Hi!  

### ISSUE THREAD

**Issue by RyanCCollins** [notwaldorf/ama#54]
Hello Monica!

I am dropping an issue to say that I like your emoji creativity 👍!  I once had the idea to install an easter egg in one of my apps where it would rain emoji on the user.  Of course, I didn't get too far with that one. I am glad to know that if I ever get that temptation again, I can fork your project!

Nice job!

Regards,

Ryan Collins

**Comment by notwaldorf** [comment]
Thanks! `emoji-rain` is just an element, so you can drop it on any page! Check out the 🎉 button on http://meowni.ca :)
