### ISSUE TITLE
obscure hobby

### ISSUE THREAD

**Issue by LuisSaybe** [notwaldorf/ama#56]
Do you currently have an obscure (doesn't have to be) hobby that is not related to programming / science / tech, et cetera?

**Comment by notwaldorf** [comment]
Oh my, I think most of my hobbies are very pedestrian, actually (baking! drawing! playing instruments! doing my nails!). I think the weirdest hobby I have is that I collect fridge magnets -- I probably have over 200 now.

**Comment by LuisSaybe** [comment]
https://giphy.com/gifs/adventure-time-nice-finn-the-human-qPcX2mzk3NmjC

**Comment by JohnLonginotto** [comment]
I have a cat. He is a fridge magnet :~|

**Comment by notwaldorf** [comment]
🐱
