### ISSUE TITLE
Montreal -> Sun Funcisco

### ISSUE THREAD

**Issue by H3dz** [notwaldorf/ama#57]
Hi from Montreal!

I recently got interested in Polymer and watched some of your videos.

I was wondering how you got to work for Google in San Francisco.

Cheers!

**Comment by notwaldorf** [comment]
Hiya! 👋 

The answer is actually quite boring -- I used to work for Google in Montreal (I worked in Chrome, on the new profiles menu), and then I just did an internal transfer to Polymer. As to how I got to work for Google in Montreal, that's also a boring answer, I'm afraid. A friend who worked there recommended me, and I went through the interviewing process and got hired.

**Comment by H3dz** [comment]
Cool, I was expecting an answer written strictly with emojis, but that's good enough!
