### ISSUE TITLE
👋 On collaborating with other googler

### ISSUE THREAD

**Issue by rakeen** [notwaldorf/ama#58]
- Does [Paul Lewis](https://youtu.be/CubrYp4cuyY) work in the polymer team?  
- Isn't he working in the London office? How do you guys [colla](https://meowni.ca/posts/web-fonts/#tl-dr)[borate](https://youtu.be/6t2JRKTCYbI?t=20m38s) then? online?

**Comment by notwaldorf** [comment]
Oh, good question! @paullewis doesn't directly work on Polymer, no. He's done perf audits of some of our stuff before, though. He works out of the London office, and we usually chat online, if we need to (or in person if I run into him when travelling, like we did for the Polymer Summit) -- the same thing happens with other dev rels that work in different offices than mine!
