### ISSUE TITLE
What's your favorite emoji set?

### ISSUE THREAD

**Issue by wbinnssmith** [notwaldorf/ama#6]
Apple, android/Google, twemoji, emoji one, etc. I like [this table](http://apps.timwhitlock.info/emoji/tables/unicode) if you haven't seen it yet.

**Comment by notwaldorf** [comment]
I used to like the Twitter emoji the most (their food emoji are super cute), but recently the Android blobs have really grown on me. <img width="30" alt="screen shot 2015-08-31 at 10 17 32 pm" src="https://cloud.githubusercontent.com/assets/1369170/9596755/1911db26-502e-11e5-8fcc-d34ab3de7bb6.png"> in particular is truly fantastic.

**Comment by 4gstudios** [comment]
Heresy!  Apple FTW (I actually go out of my way to switch my Android phone emoji font).
