### ISSUE TITLE
how to use tweemoji

### ISSUE THREAD

**Issue by shanisebarona** [notwaldorf/ama#66]
hi monica! super inspired by your work! so much so, that in my recent re-design of my wbesite, i tried using twemoji (https://github.com/ellekasai/twemoji-awesome) but it doesn't seem to be working for me. i get a build fail and github tells me i need to `git submodule init` which i tried and alas no luck. it could be that it's just super outdated (as the repo is not maintained)

so basically my question is do you know if there are any css alternatives to tweemoji https://github.com/ellekasai/twemoji-awesome or a way to include twemoji on a static site?

thanks in advance :)

**Comment by notwaldorf** [comment]
I included twemoji on a static site via the instructions from https://github.com/twitter/twemoji:
```
<script src="//twemoji.maxcdn.com/2/twemoji.min.js?2.3.0"></script>
```
