### ISSUE TITLE
Polymer 2.x Cheat Sheet - Extending an element

### ISSUE THREAD

**Issue by rene-lindner-isw** [notwaldorf/ama#68]
Found your Cheat Sheet while looking for an solution to extend iron-ajax.

Tried `extends customElement.get('parent-element')`, but got an error that customElement does not exist.
Shouldn't it be `extends window.customElements.get('parent-element')` instead?

Thanks for the sheet, helped me alot :)

**Comment by notwaldorf** [comment]
Oh yeah, that's totally a typo! Thanks for catching it :) Fixed!
