### ISSUE TITLE
Polymer 2 NOT working in IE11

### ISSUE THREAD

**Issue by ghost** [notwaldorf/ama#69]
Monica,
    I have a Polymer 2 application that's NOT working in IE11, as you can see in this issue I didn't even open myself:
https://github.com/Polymer/polymer-cli/issues/779
I understand that you are all working hard on this, and I do not pretend anything specific, but since we have to deliver the application before the end of the month, I'm on the verge of downgrading all the application to work in Polymer 1, that looks more reliable in terms of browser compatibility.
Moreover, just yesterday I found that there is a new version of Polymer CLI (1.3.0) but the bug is not solved (and I think that it's a really BIG bug!).
What I'm asking is just a feeling: could you just look around, talk to someone, and tell the audience (I'm not the only one to have this problem...) if the feeling that the bug will be solved (and in general that we will have compatibility with IE11) or Polymer 2 is in the end still not so mature, and we have to stick, for production, to Polymer 1 still for more time to come?
Thanks anyway for your support!

**Comment by notwaldorf** [comment]
For Polymer issues, please file bugs on _Polymer_. This is my _personal_ ama, not a work-related repository, and I only saw this issue by accident. Polymer 2 uses ES6 code, which on IE11 isn't supported without transpilling to ES5. You're probably not doing that. Please take a look at https://www.polymer-project.org/2.0/docs/about_20#ecmascript-2015-a.k.a.es6, and ask questions on the Slack channel/the Polymer repo if you have any more questions.
