### ISSUE TITLE
Polymer Patterns

### ISSUE THREAD

**Issue by megamegax** [notwaldorf/ama#74]
Hi!

I made a lot of search according to this subject but found nothing promising. If I want to do complex apps in Polymer. (I know I could there are a lots of components for that) I always run into the issue of it just become a mess.

In Android I can use architecture patterns like MVP, MVVM to keep my code in shape. I was looking for a tutorial of MVVM for example using Polymer but found nothing. Also In every example everything is in one file. one my-element.html with css, html, js included. Why is this the best practice? It would be so nice to separate stuffs because I see for one elmenet it is good to have everything in one file. But when I want to do something more than just one small component... then mess comes very very soon :) 

Do you have any advice?

**Comment by notwaldorf** [comment]
Hiya!

Sorry, I completely forgot to check this repo recently. A couple of answers, out of order:
- we prefer keeping the element's html/css/js in the same file. A component is standalone, and can't really work without its html/js, so keeping it all together makes sense. There are definitely teams that separate that, but we don't. I also like to keep it as an internal metric of how big that element is becoming: if the html/css/js is SO big in the same file that it's unmaintainable, it's probably time to refactor it a bit, and break it out into smaller elements
- for building apps, the mantra is "properties down, events up" to communicate between elements. Polymer isn't a framework, so it doesn't have any really strong opinions about how you should organize your code, as a result. Here are some talks about how to structure your apps that might help, though:
- kevin schaaf's end-to-end apps with polymer: https://www.youtube.com/watch?v=0A-2BhEZiM4
- gray norton's data flow in polymer elements: https://www.youtube.com/watch?v=pAW4YDLtPVs

**Comment by megamegax** [comment]
thank you! :)
  Since then I was watching videos about polymer + redux, I feel like it is a good solution for communicating between components ^^
