### ISSUE TITLE
Broken links in chromium-101 blog post

### ISSUE THREAD

**Issue by hassansalehe** [notwaldorf/ama#75]
Hi Monica,

I was recently reading your illustrated guide about [contributing to Chromium](https://meowni.ca/posts/chromium-101/). Thank you for the well-written article.  However, I did come across two dead links that I'm willing to fix if your blog is on Github -- I checked but could not locate. Below are details if you would like to fix them.

The first broken link is https://github.com/notwaldorf/.not-quite-dotfiles/blob/master/chrome which is used in this excerpt:

> However, I’ll tell you about the custom [things](https://github.com/notwaldorf/.not-quite-dotfiles/blob/master/chrome) that I use that aren’t on that page, which I’m pretty proud of.

I investigated your ".not-quite-dotfiles" repo and it seems that you moved the "chrome" file to  "zsh/chrome" in commit [# 0b78b54](https://github.com/notwaldorf/.not-quite-dotfiles/commit/0b78b54c4ff0ad08088932d504c96984798946bb). The correct link should be https://github.com/notwaldorf/.not-quite-dotfiles/blob/master/zsh/chrome

The second broken link is https://github.com/notwaldorf/not-quite-dotfiles/blob/master/chrome#L15 found in the bullet point:
>  I have a fancy set of [aliases](https://github.com/notwaldorf/not-quite-dotfiles/blob/master/chrome#L15) like make_ and go_, so that I don’t have to remember about which flags I want to run Chrome with. They come in doskey variants on Windows

The correct link should be https://github.com/notwaldorf/.not-quite-dotfiles/blob/master/zsh/chrome#L15

Thank you.

**Comment by notwaldorf** [comment]
Oh! Thanks! I refactored that repo and totally forgot I mentioned it anywhere else. Fixed!
