### ISSUE TITLE
Slide Design

### ISSUE THREAD

**Issue by rambleraptor** [notwaldorf/ama#83]
You always seem to have really well designed slides! Any tips on good slide design?

**Comment by notwaldorf** [comment]
Thanks! Glad you like them!
My biggest advice is:
- big text, no bullets
- try to group sections by content, and make a section look coherent
- when showing code, use "code goggles" (highlight the line of code you're looking at, fade everything else)

If you want to read more, [speaking.io](https://speaking.io/) is an amazing resource for all talk related things, and has a whole section on slide design.
