### ISSUE TITLE
Sparing actual/diff PNGs from failures of Puppeteer screenshot diff tests in CI?

### ISSUE THREAD

**Issue by anishkny** [notwaldorf/ama#91]
Hi @notwaldorf !

Loved your post on [Automatic visual diffing with Puppeteer](https://meowni.ca/posts/2017-puppeteer-tests/). I am trying to setup Puppeteer-screenshot diff tests for my repo [vuepress-base](https://github.com/anishkny/vuepress-base) with TravisCI. 

Any best practices on how to spare actual and diff screenshots in case of failure in TravisCI? 

Cheers!

**Comment by notwaldorf** [comment]
What do you mean by `spare`? Do you mean `see`? If so, I haven't found a super good way other than dumping the base64 data as a string, and then displaying it somewhere (with a `data:image/png;base64,...` tag ). [Here](https://github.com/Polymer/pwa-starter-kit/blob/master/test/integration/visual.js#L107) is an example of how i dump the actual screenshot, but if you move this to the bottom, you can dump the `${view}-diff.png` diff instead).

**Comment by anishkny** [comment]
Hey thanks for the reply!

Yes, I meant `see` 😃 . I could figure out how to see the screenshots locally, but if my screenshot diff test fails in [CI](https://travis-ci.org/anishkny/vuepress-base/builds/389036412), how do I see expected/actual/diff PNGs?

The best I could come up with is to upload the PNGs in case of failure to S3/surge.sh or similar. E.g.: http://vuepress-base.surge.sh generated by [this code](https://github.com/anishkny/vuepress-base/blob/tests/test/test.screenshot.js#L60).

Also, I am seeing failures because my golden screenshot is generated on a Mac, but my CI runs it against Linux. And if I adjust the `pixelmatch` `threshold` too much, I am afraid the test might silently pass.

Wondering how you handled these situations s'all...
