### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by Bezalja** [notwaldorf/ama#95]
Thank you very much for your [awesome post on RL](https://meowni.ca/posts/rl-with-otters/) :trophy:
It reminds me of _why's poignant guide to ruby :heart_eyes_cat:
Maybe you should write a guide to RL? :smiley_cat:

**Comment by notwaldorf** [comment]
Yay, glad you liked it!

Heh, there is already a guide to RL! [Sutton and Barto's book](http://incompleteideas.net/book/bookdraft2017nov5.pdf) is perfect, imo! It taught me almost everything I know about RL! 😍
