### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by RossLegalSuite** [notwaldorf/ama#97]
Im about to dive into creating a PWA app,

Is it still the way to go?

Would you suggest starting Polymer 3 or 2?

**Comment by notwaldorf** [comment]
PWAs are always the way to go, imo, if you want to only write code once and have it work on many different platforms. I'd recommend taking a look at the [pwa-starter-kit](https://github.com/Polymer/pwa-starter-kit), which we built exactly to help with these questions! 😄
